redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\xampp\\htdocs\\cse\\frontstt\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]
node_bundler = "esbuild"
external_node_modules = ["express"]

[build]
publish = "C:\\xampp\\htdocs\\cse\\frontstt\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\xampp\\htdocs\\cse\\frontstt\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]